AUGMENTATION : True
IMAGE_SIZE : [224,224,3]   #vg16 model
BATCH_SIZE : 16
INCLUDE_TOP : False  #only take cnn part
EPOCHS : 1     #training on local machine thats why
CLASSES : 2    
WEIGHTS : imagenet
LEARNING_RATE : 0.01 